{% set name = "qtmodern" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57e62617656494a9d8a27ac3bd51ae3ae61a265f43b92d6f6ea59dc8bed2179d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - qtpy

test:
  imports:
    - qtmodern

about:
  home: https://github.com/gmarull/qtmodern
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PyQt/PySide Widgets Modern User Interface
  description: |
    qtmodern is a Python package aimed to make PyQt/PySide applications look
    better and consistent on multiple platforms. It provides a custom frameless
    window and a dark theme. In order to be compatible with multiple Python Qt
    wrappers QtPy is used.

extra:
  recipe-maintainers:
    - hmaarrfk
